spring.application.name=HiveMind

# default active profile: change to 'prod' for production
spring.profiles.active=dev

# Common JPA settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect